-- MySQL Script generated by MySQL Workbench
-- Sun Feb 22 21:01:29 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dotd_parser
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dotd_parser
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dotd_parser` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `dotd_parser` ;

-- -----------------------------------------------------
-- Table `dotd_parser`.`enchantments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dotd_parser`.`enchantments` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `proc_name` VARCHAR(128) NOT NULL,
  `proc_desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  INDEX `name_IDX` (`name` ASC),
  INDEX `proc_name_IDX` (`proc_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dotd_parser`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dotd_parser`.`equipment` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NULL,
  `attack` INT NULL,
  `defense` INT NULL,
  `perception` INT NULL,
  `rarity` INT NULL,
  `value_gold` INT NULL,
  `value_gtoken` INT NULL,
  `questReq` INT NULL,
  `unique` TINYINT(1) NULL,
  `canEnchant` TINYINT(1) NULL,
  `equipType` INT NULL,
  `hlt` INT NULL,
  `eng` INT NULL,
  `sta` INT NULL,
  `hnr` INT NULL,
  `atk` INT NULL,
  `def` INT NULL,
  `power` INT NULL,
  `dmg` INT NULL,
  `deflect` INT NULL,
  `lore` VARCHAR(4096) NULL,
  `proc_name` VARCHAR(128) NULL,
  `proc_desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  INDEX `name_IDX` (`name` ASC),
  INDEX `proc_name_IDX` (`proc_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dotd_parser`.`generals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dotd_parser`.`generals` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NULL,
  `attack` INT NULL,
  `defense` INT NULL,
  `race` INT NULL,
  `role` INT NULL,
  `rarity` INT NULL,
  `value_gold` INT NULL,
  `value_credits` INT NULL,
  `questReq` INT NULL,
  `source` INT NULL,
  `buffType` INT NULL,
  `lore` VARCHAR(4096) NULL,
  `proc_name` VARCHAR(128) NULL,
  `proc_desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  INDEX `name_IDX` (`name` ASC),
  INDEX `proc_name_IDX` (`proc_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dotd_parser`.`legions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dotd_parser`.`legions` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NULL,
  `num_gen` INT NULL,
  `num_trp` INT NULL COMMENT '  ',
  `bonus` INT NULL,
  `bonusSpecial` INT NULL,
  `bonusText` VARCHAR(128) NULL,
  `rarity` INT NULL,
  `value_gold` INT NULL,
  `value_credits` INT NULL,
  `canpurchase` TINYINT(1) NULL,
  `questReq` INT NULL,
  `lore` VARCHAR(4096) NULL,
  `proc_name` VARCHAR(128) NULL,
  `proc_desc` VARCHAR(4096) NULL,
  `specification` VARCHAR(4096) NULL,
  `general_format` VARCHAR(4096) NULL,
  `troop_format` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  INDEX `name_IDX` (`name` ASC),
  INDEX `proc_name_IDX` (`proc_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dotd_parser`.`mounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dotd_parser`.`mounts` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NULL,
  `attack` INT NULL,
  `defense` INT NULL,
  `perception` INT NULL,
  `rarity` INT NULL,
  `value_gold` INT NULL,
  `value_credits` INT NULL,
  `questReq` INT NULL,
  `unique` TINYINT(1) NULL,
  `hlt` INT NULL,
  `eng` INT NULL,
  `sta` INT NULL,
  `hnr` INT NULL,
  `atk` INT NULL,
  `def` INT NULL,
  `power` INT NULL,
  `dmg` INT NULL,
  `deflect` INT NULL,
  `lore` VARCHAR(4096) NULL,
  `proc_name` VARCHAR(128) NULL,
  `proc_desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  INDEX `name_IDX` (`name` ASC),
  INDEX `proc_name_IDX` (`proc_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dotd_parser`.`troops`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dotd_parser`.`troops` (
  `id` INT UNSIGNED NOT NULL,
  `name` VARCHAR(128) NULL,
  `attack` INT NULL,
  `defense` INT NULL,
  `race` INT NULL,
  `role` INT NULL,
  `rarity` INT NULL,
  `value_gold` INT NULL,
  `value_credits` INT NULL,
  `canpurchase` TINYINT(1) NULL,
  `questReq` INT NULL,
  `source` INT NULL,
  `buffType` INT NULL,
  `lore` VARCHAR(4096) NULL,
  `proc_name` VARCHAR(128) NULL,
  `proc_desc` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  INDEX `name_IDX` (`name` ASC),
  INDEX `proc_name` (`proc_name` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

